services:
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command:
      - "server"
      - "/data/minio"
      - "--console-address"
      - ":9001"
    volumes:
      - minio:/data/minio

  mongo-beijing-router:
    image: mongo:5.0.9
    container_name: mongo-beijing-router
    hostname: mongo-beijing-router
    command: mongos --configdb config-rs/mongo-beijing-config:27017,mongo-hong-kong-config:27017 --bind_ip_all --port 27017
    ports:
      - 27017:27017
    depends_on:
      - mongo-beijing-config
      - mongo-hong-kong-config
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  mongo-hong-kong-router:
    image: mongo:5.0.9
    container_name: mongo-hong-kong-router
    hostname: mongo-hong-kong-router
    command: mongos --configdb config-rs/mongo-beijing-config:27017,mongo-hong-kong-config:27017 --bind_ip_all --port 27017
    ports:
      - 27018:27017
    depends_on:
      - mongo-beijing-config
      - mongo-hong-kong-config
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  mongo-beijing-config:
    image: mongo:5.0.9
    container_name: mongo-beijing-config
    hostname: mongo-beijing-config
    command: mongod --configsvr --replSet config-rs --port 27017 --dbpath /data/db
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo-beijing-config:/data/db
    restart: always

  mongo-hong-kong-config:
    image: mongo:5.0.9
    container_name: mongo-hong-kong-config
    hostname: mongo-hong-kong-config
    command: mongod --configsvr --replSet config-rs --port 27017 --dbpath /data/db
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo-hong-kong-config:/data/db
    restart: always

  mongo-shared-shard-1:
    image: mongo:5.0.9
    container_name: mongo-shared-shard-1
    hostname: mongo-shared-shard-1
    command: mongod --shardsvr --replSet shared-shard-rs --port 27017 --dbpath /data/db
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo-shared-shard-1:/data/db
    restart: always

  mongo-beijing-shard-1:
    image: mongo:5.0.9
    container_name: mongo-beijing-shard-1
    hostname: mongo-beijing-shard-1
    command: mongod --shardsvr --replSet beijing-shard-rs --port 27017 --dbpath /data/db
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo-beijing-shard-1:/data/db
    restart: always

  mongo-beijing-shard-2:
    image: mongo:5.0.9
    container_name: mongo-beijing-shard-2
    hostname: mongo-beijing-shard-2
    command: mongod --shardsvr --replSet beijing-shard-rs --port 27017 --dbpath /data/db
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo-beijing-shard-2:/data/db
    restart: always

  mongo-hong-kong-shard-1:
    image: mongo:5.0.9
    container_name: mongo-hong-kong-shard-1
    hostname: mongo-hong-kong-shard-1
    command: mongod --shardsvr --replSet hong-kong-shard-rs --port 27017 --dbpath /data/db
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo-hong-kong-shard-1:/data/db
    restart: always

  mongo-hong-kong-shard-2:
    image: mongo:5.0.9
    container_name: mongo-hong-kong-shard-2
    hostname: mongo-hong-kong-shard-2
    command: mongod --shardsvr --replSet hong-kong-shard-rs --port 27017 --dbpath /data/db
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo-hong-kong-shard-2:/data/db
    restart: always

  redis-beijing:
    image: redis
    container_name: redis-beijing
    ports:
      - 6379:6379
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis-hong-kong:
    image: redis
    container_name: redis-hong-kong
    ports:
      - 6380:6379
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  mongo-beijing-router:
  mongo-hong-kong-router:

  mongo-beijing-config:
  mongo-hong-kong-config:

  mongo-shared-shard-1:
  mongo-beijing-shard-1:
  mongo-beijing-shard-2:
  mongo-hong-kong-shard-1:
  mongo-hong-kong-shard-2:

  minio:
